name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  #    - name: Update packages
  #      run: |
  #        sudo apt-get update -y
  #        sudo apt-get upgrade -y

      - name: Remove conflicting packages
        run: |
          sudo apt-get remove -y containerd
          sudo apt-get clean
          sudo apt-get update
          sudo apt-get autoremove -y
          sudo apt-get install -y containerd.io



      - name: Build and push Docker image
        run: |
          docker build -t docker-test .
          docker login -u 10449 -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker tag docker-test 10449/docker-test
          docker push 10449/docker-test

      - name: Disable strict host key checking
        run: echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: SSH into server and deploy
        run: |
          ssh  root@95.130.227.6 "docker pull 10449/docker-test && docker-compose up -d"
